### ISSUE TITLE
BE-SignUp unable to signup for unknown reason Error

### ISSUE THREAD

**Issue by KunSu** [KunSu/hunger_at_home#24]
{"email": "kunsu@gmail.com", "password": "1234", "firstName": "Kun", "lastName": "Su", "phoneNumber": "1234567890", "userIdentity": "admin", "companyID": "1", "secureQuestion": "something", "secureAnswer": "something"}

{
    "httpCode": "404",
    "message": "This email address is already taken"
}

1. The email address has not been taken
2. Let's make secureQuestion and secureAnswer optional for alpha version
3. password will be encoded via MD5 before API call
4. User should not able to sign up "Admin" account
5. The "httpCode" inside the response body is not necessary, it can be removed.

![image](https://user-images.githubusercontent.com/55034108/94387203-4d175500-00fe-11eb-9fa5-f04bcc68c48c.png)

**Comment by zijianguan0204** [comment]
1. Done. DB handling error
2. Done
3. It would be done in front end after discussion
4. It can be removed from the drop down options from frontend
5. Done
