### ISSUE TITLE
Driver list display issue

### ISSUE THREAD

**Issue by zijianguan0204** [KunSu/hunger_at_home#28]
The driver order inside account of admin used backend API which will return all donations. Is it supposed to display all orders that are related to current employees?

**Comment by KunSu** [comment]
It is fixed. Now FE needs to fetch all orders from BE using `admin/$userID/orders/donation/status/ `, and then do the filtering to display the employee list with properly status ('approved', 'pickuped', 'delivered').
The filtering should be handled by BE for the next version.

FE should pass multiple statuses with the same API `admin/$userID/orders/donation/status/ `

The actual URL will be like this: `admin/$userID/orders?orderType=donation&status=approved,pickuped,delivered`
`admin/$userID/orders?orderType=all&status=all` to return all orders

Sample: https://www.searchenginejournal.com/technical-seo/url-parameter-handling
