### ISSUE TITLE
Donation drop off option

### ISSUE THREAD

**Issue by KunSu** [KunSu/hunger_at_home#31]

**Comment by KunSu** [comment]
Default drop off address for Hunger at Home is 1534 Berger Drive, San Jose, CA 95112

**Comment by KunSu** [comment]
@zijianguan0204 Pickup donation will call the `api/order` the same way we did before.
The new Dropoff donation will call the `api/order` without 'pickUpTime' in the body
You can pull the latest version to check your code, but do **NOT** push to production before the next version is released.
The default H@H address ID will be 1.

Since the pickUpTime is missing for Drop off donation order. Plz, double-check the logic related to pickUpTime as they need to return valid values. Don't close this issue until we release a new version. Feel free to comment.

**Comment by zijianguan0204** [comment]
For droppedoff donation, you will start making an order as what we used to do without adding pickuptime entry inside the body. As the data is not null, backend system will handle it and "0000-00-00 00:00:00" will fill the entry. The functionality can be done using the existing API (post)order, payload or url will not be changed at this point
