### ISSUE TITLE
Admin Donation Page Missing Operations

### ISSUE THREAD

**Issue by zijianguan0204** [KunSu/hunger_at_home#57]
![image](https://user-images.githubusercontent.com/31665442/105615377-15a37700-5d85-11eb-9d28-f16b7c5736ba.png)
According to the diagram we discussed, a pending order can be either 
1. Admin edit first and set the order status to approved, then the user should confirm it 
2. Admin does not need to edit the order, so Admin can set the order status from pending to confirmed

The snapshot above shows that there is no confirmed button, and the order can not go directly to "droppedoff" status without being confirmed first

Also missing "cancel" operation

**Comment by KunSu** [comment]
> Admin edit first and set the order status to approved, then the user should confirm it
> Admin does not need to edit the order, so Admin can set the order status from pending to confirmed

The edit operation for Admin is NOT implemented yet.

> The snapshot above shows that there is no confirmed button, and the order can not go directly to "droppedoff" status without being confirmed first

Confirmed operation is only available for Donor/Recipient
