### ISSUE TITLE
Icon replacement

### ISSUE THREAD

**Issue by pxlin0223** [KunSu/hunger_at_home#60]
**Company page icon replace**

Company Name Icon: business
501c3 FED ID: description
EIN ID: assignment
Address: place
City: location_city
State: flag
zipcode: near_me

**Tap bar icon replace**
Donate & Request: add_circle

**Comment by KunSu** [comment]
@pxlin0223 Thank you for the suggestion. And besides the company page, plz take a look at all pages. Such as the add new address page. We would like to replace all the happy face icons with a proper icon.

**Comment by pxlin0223** [comment]
@KunSu for the "add new address page", you can use the same icons as provided:
Address: place
City: location_city
State: flag
zipcode: near_me
